### ISSUE TITLE
Federation issue with Hometown

### ISSUE THREAD

**Issue by wakest** [Automattic/wordpress-activitypub#939] opened 2024-10-11 22:08 UTC
### Quick summary

there is a discussion here https://niagara.social/@kostyn/113286764577822977 already but to summarize what I discovered:

[this post](https://kostyn.ca/fuck-sustainable-development-goals-have-yall-ever-heard-of-communism-reviewing-kohei-saitos-slow-down-the-degrowth-manifesto/) is not showing up when searched for from either merveilles.town or niagara.social which are both running [Hometown](https://github.com/hometown-fork/hometown/) (a fork of Mastodon by @dariusk) so it seems maybe the issue is with compatibility of Hometown and WordPress AP. Seems Hometown still [has a lot of users](https://fedidb.org/software/hometown) tho so still seems important to solve from one side or the other

### Steps to reproduce

Search [this post](https://kostyn.ca/fuck-sustainable-development-goals-have-yall-ever-heard-of-communism-reviewing-kohei-saitos-slow-down-the-degrowth-manifesto/) on a Hometown instance

### What you expected to happen

the post shows up

### What actually happened

the post is not found

### Impact

All

### Available workarounds?

No and the platform is unusable

**Comment by pfefferle** [comment] 2024-10-14 10:53
Could be fixed by https://github.com/Automattic/wordpress-activitypub/pull/931 but I will have another look!

**Comment by dariusk** [comment] 2024-11-05 17:23
Okay, looking into this! Basically going to log my process here as I go.

On a clean Hometown install when I put `https://kostyn.ca/fuck-sustainable-development-goals-have-yall-ever-heard-of-communism-reviewing-kohei-saitos-slow-down-the-degrowth-manifesto/` into the search bar of the web client and search, I get a "500" error reported on the client side, and I get this in the logs:

```log
08:20:48 web.1     | Completed 500 Internal Server Error in 6606ms (ActiveRecord: 58.1ms | Allocations: 180111)
08:20:48 web.1     | 
08:20:48 web.1     | 
08:20:48 web.1     |   
08:20:48 web.1     | ArgumentError (wrong number of arguments (given 1, expected 0)):
08:20:48 web.1     |   
08:20:48 web.1     | app/lib/activitypub/activity/create.rb:139:in `initialize'
08:20:48 web.1     | app/lib/activitypub/activity/create.rb:167:in `new'
08:20:48 web.1     | app/lib/activitypub/activity/create.rb:167:in `process_inline_images'
08:20:48 web.1     | app/lib/activitypub/activity/create.rb:81:in `process_status'
08:20:48 web.1     | app/lib/activitypub/activity/create.rb:58:in `block in create_status'
08:20:48 web.1     | app/models/concerns/lockable.rb:12:in `block (2 levels) in with_redis_lock'
08:20:48 web.1     | app/models/concerns/lockable.rb:10:in `block in with_redis_lock'
08:20:48 web.1     | app/lib/redis_configuration.rb:10:in `with'
08:20:48 web.1     | app/models/concerns/redisable.rb:9:in `with_redis'
08:20:48 web.1     | app/models/concerns/lockable.rb:9:in `with_redis_lock'
08:20:48 web.1     | app/lib/activitypub/activity/create.rb:52:in `create_status'
08:20:48 web.1     | app/lib/activitypub/activity/create.rb:15:in `perform'
08:20:48 web.1     | app/services/activitypub/fetch_remote_status_service.rb:55:in `call'
08:20:48 web.1     | app/services/fetch_remote_status_service.rb:12:in `call'
08:20:48 web.1     | app/services/resolve_url_service.rb:28:in `process_url'
08:20:48 web.1     | app/services/resolve_url_service.rb:16:in `call'
08:20:48 web.1     | app/services/search_service.rb:77:in `url_resource'
08:20:48 web.1     | app/services/search_service.rb:19:in `block in call'
08:20:48 web.1     | app/services/search_service.rb:15:in `call'
08:20:48 web.1     | app/controllers/api/v2/search_controller.rb:33:in `search_results'
08:20:48 web.1     | app/controllers/api/v2/search_controller.rb:12:in `index'
08:20:48 web.1     | app/controllers/concerns/localized.rb:11:in `set_locale'
08:20:48 web.1     | lib/mastodon/rack_middleware.rb:9:in `call'
08:20:48 web.1     | lib/public_file_server_middleware.rb:18:in `call'
08:20:48 sidekiq.1 |   Account Load (0.3ms)  SELECT "accounts"."id", "account
```

Sooo the problem is in my `process_inline_images` function. I'm opening an issue on Hometown shortly that will link back to here for reference.

**Comment by pfefferle** [comment] 2024-11-07 11:05
I will close this for now, but we can still discuss updates here!

**Closed as completed by pfefferle** 2024-11-07 11:05 UTC
Labels: Bug, Needs triage
