### ISSUE TITLE
Post not showing up at Mastodon

### ISSUE THREAD

**Issue by jeckman** [Automattic/wordpress-activitypub#873] opened 2024-08-28 20:59 UTC
### Quick summary

I run ActivityPub on WordPress here: @john@goatless.org 

To test it, I followed myself from mastodon.social:  https://mastodon.social/@john@goatless.org 

I don't see any posts since Sept 2023, but I post regularly. 

I tried unfollowing and refollowing - but I'm stuck on even how to troubleshoot what's going on here not knowing where the problem might be 

### Steps to reproduce

Visit  https://mastodon.social/@john@goatless.org  or find the user @john@goatless.org on any ActivityPub site 

### What you expected to happen

Posts should appear, including those written this week 

### What actually happened

I see nothing newer than Sept 28, 2023 

### Impact

One

### Available workarounds?

No and the platform is unusable

**Comment by pfefferle** [comment] 2024-08-29 05:37
Can you install a cron plugin to check if there are some blocking wp_crons?

**Comment by pfefferle** [comment] 2024-08-29 05:39
Or have you disabled or maybe misconfigured your `WP_Cron` setup?

**Comment by solarbirdy** [comment] 2024-08-29 21:46
I'm also seeing this on one of my sites - @status@status.murkworks.net - it was working fine and then it just stopped. I've been meaning to come report it. WP site is at https://status.murkworks.net and here's a view of the profile from my Mastodon instance https://mastodon.murkworks.net/@status@status.murkworks.net so.

I'm able to refresh the profile fine so it is talking to the world. I'm getting 200 OK in response to hits on wp-cron.php and I'm having that run every five minutes at the system level, but it doesn't help.

**Comment by jeckman** [comment] 2024-08-30 13:03
Solarbirdy - since you're also running a mastodon instance, is there anything logged on that side? I'm not running one and therefore stuck on how to debug

**Comment by pfefferle** [comment] 2024-08-30 18:21
Does Mastodon index your posts if you put the permalink of a new post into the search field?

I am currently at vacation, will run some tests when I am back!

**Comment by solarbirdy** [comment] 2024-08-30 18:34
@jeckman - As in, apache logs or something? Not that I've found.

@pfefferle - That's interesting. YES. And the post once searched for appears, but _only_ on the individual author profile (as viewed from Mastodon), and not on the blog profile (also as viewed from mastodon).

I searched [for the most recent post](https://status.murkworks.net/2024/08/17/web-services-back-online/), now it appears in the [@solarbird@status.murkworks.net](https://mastodon.murkworks.net/@solarbird@status.murkworks.net) profile as it should:

![image](https://github.com/user-attachments/assets/7965e686-181c-4262-97f7-8021230eb328)

But it still does not appear in the [@status@status.murkworks.net](https://mastodon.murkworks.net/@status@status.murkworks.net) profile:

![image](https://github.com/user-attachments/assets/8f3a3f1e-2864-4223-a742-3a178b12d6d3)

And none of the posts between that and the older ones have federated.

**Comment by jeckman** [comment] 2024-08-30 18:38
Mine do show up in mastodon if I search for them by permalink, and then after that they show up in the profile

**Comment by pfefferle** [comment] 2024-08-30 19:22
Ok, then it does not seem to be a caching issue, but a distribution thing! @solarbirdy can you check if your blogs domain is on a block list of your instance?

**Comment by harcesz** [comment] 2024-09-06 21:33
Got the same problem with @kolektyw@adapulawska.org vs individual blogs that seem to work fine, tested on two instances nothing suggest a ban.

**Comment by hardillb** [comment] 2024-09-26 22:23
I believe I'm seeing this as well. Specifically I have 2 mastodon users. The first follows both the overall blog profile and the author profile. The second is only following the blog profile.

The user following the author sees the posts but not the boost by the blog profile, and the user only following the blog profile is not seeing the posts getting boosted by the blog profile.

Looking at the blog profile via my mastodon instance I do see one boosted post from the 13th Sept, but not the newer post

blog profile: @blog.hardill.me.uk@blog.hardill.me.uk
author profile @hardillb@blog.hardill.me.uk

**Comment by pfefferle** [comment] 2024-09-27 07:14
Hey @hardillb 👋

Have checked if you have some blocking WP_Crons in your queue?

**Comment by hardillb** [comment] 2024-09-27 07:31
I don't think so, the health check page shows all is good.

`wcli cron test` reports `Success: WP-Cron spawning is working as expected.`

`wcli cron event list` shows 

```
+------------------------------------+---------------------+-----------------------+------------+
| hook                               | next_run_gmt        | next_run_relative     | recurrence |
+------------------------------------+---------------------+-----------------------+------------+
| wp_update_user_counts              | 2024-09-27 07:27:43 | 23 seconds            | 12 hours   |
| action_scheduler_run_queue         | 2024-09-27 07:27:53 | 33 seconds            | 1 minute   |
| jetpack_sync_full_cron             | 2024-09-27 07:28:03 | 43 seconds            | 5 minutes  |
| jetpack_sync_cron                  | 2024-09-27 07:30:34 | 3 minutes 14 seconds  | 5 minutes  |
| jetpack_clean_nonces               | 2024-09-27 07:34:38 | 7 minutes 18 seconds  | 1 hour     |
| wp_privacy_delete_old_export_files | 2024-09-27 07:43:57 | 16 minutes 37 seconds | 1 hour     |
| w3_objectcache_cleanup             | 2024-09-27 07:52:34 | 25 minutes 14 seconds | 1 hour     |
| activitypub_update_followers       | 2024-09-27 07:56:11 | 28 minutes 51 seconds | 1 hour     |
| wp_version_check                   | 2024-09-27 08:04:17 | 36 minutes 57 seconds | 12 hours   |
| wp_update_themes                   | 2024-09-27 08:04:22 | 37 minutes 2 seconds  | 12 hours   |
| wp_update_plugins                  | 2024-09-27 08:06:30 | 39 minutes 10 seconds | 12 hours   |
| w3_pgcache_cleanup                 | 2024-09-27 08:20:21 | 53 minutes 1 second   | 1 hour     |
| wp_scheduled_auto_draft_delete     | 2024-09-27 08:23:36 | 56 minutes 16 seconds | 1 day      |
| jp_purge_transients_cron           | 2024-09-27 09:53:09 | 2 hours 25 minutes    | 1 day      |
| activitypub_cleanup_followers      | 2024-09-27 10:56:11 | 3 hours 28 minutes    | 1 day      |
| jetpack_v2_heartbeat               | 2024-09-27 16:27:26 | 9 hours               | 1 day      |
| jp_sitemap_cron_hook               | 2024-09-27 17:28:57 | 10 hours 1 minute     | 12 hours   |
| wp_scheduled_delete                | 2024-09-27 17:49:47 | 10 hours 22 minutes   | 1 day      |
| recovery_mode_clean_expired_keys   | 2024-09-27 19:26:52 | 11 hours 59 minutes   | 1 day      |
| delete_expired_transients          | 2024-09-27 20:04:53 | 12 hours 37 minutes   | 1 day      |
| akismet_scheduled_delete           | 2024-09-28 01:12:47 | 17 hours 45 minutes   | 1 day      |
| wp_site_health_scheduled_check     | 2024-09-28 08:11:42 | 1 day                 | 1 week     |
| wp_delete_temp_updater_backups     | 2024-10-01 23:08:38 | 4 days 15 hours       | 1 week     |
+------------------------------------+---------------------+-----------------------+------------+

```

Let me know if there is another way to test/check

**Comment by pfefferle** [comment] 2024-09-27 07:56
Could there be a race condition? Was there someone following that account when you published the post?

**Comment by hardillb** [comment] 2024-09-27 07:58
No, the accounts have been following for over a week and the last publish was yesterday. The blog profile has only boosted one post back on the 13th and none since.

**Comment by pfefferle** [comment] 2024-09-27 07:59
and you have enabled "Blog-Profile" and "Author-Profiles" in the settings?

**Comment by hardillb** [comment] 2024-09-27 08:02
Yep, running the defaults

![image](https://github.com/user-attachments/assets/bd7851b3-4061-4f30-99c2-7517b0ab8409)

**Comment by pfefferle** [comment] 2024-09-27 08:04
Do you use caching plugins?

**Comment by hardillb** [comment] 2024-09-27 08:08
Yes, I have W3 Total Cache installed with these 3 drop-ins enabled

![image](https://github.com/user-attachments/assets/f54a5e13-d5c6-4683-b3bd-3c35f0c6f4ec)

**Comment by pfefferle** [comment] 2024-09-27 08:11
Maybe this is the problem. W3 Total Cache has some issues with content negotiation: https://github.com/Automattic/wordpress-activitypub/wiki/Caching

**Comment by hardillb** [comment] 2024-09-27 08:13
OK, I'll have a look at the caching settings/plugin, but out of curiosity why would this only block the blog profile and not the author profiles?

**Comment by pfefferle** [comment] 2024-09-27 08:23
Only an assumption! It seems like a random thing (it worked one time) and that's why I assume the caching. When a caching plugin does not support content negotiation, it depends on the file in the cache. If it is the JSON it might work, otherwise it might break.

**Comment by hardillb** [comment] 2024-09-27 11:11
Yep, if I turn off the object caching things look to be working (well I get JSON back if I pass a `Accept: application/activity+json` header when testing with curl.

I'll raise an issue with W3 Total Cache

**Comment by pfefferle** [comment] 2024-09-27 11:30
And as I said, we also try to work against that issue: https://github.com/Automattic/wordpress-activitypub/pull/894

**Comment by hardillb** [comment] 2024-09-29 08:41
Just to come back to this, It turns out it's not the Object Cache, but the Page Cache that is the problem. Also using Redis rather than Disk: Enhanced appears to work correctly on a test setup

**Comment by pfefferle** [comment] 2024-09-29 11:30
Oh yes, it's always the page cache, because it could cache the wrong representation, if it does not use different buckets based on the accept header. Sorry if I was not clear about that!

**Comment by harcesz** [comment] 2024-10-01 11:03
I'll do a deeper dive later, but seems I'm also still having this/similar issue; post show up on mastodon a day later, with the correct posting hour, and so would be missed by most. Less then ideal. But I'm not sure if it's somehow not a mastodon issue, as some online debug tool fetches correct and up to date data... No catching on the website.

**Comment by pfefferle** [comment] 2024-10-01 11:41
@harcesz the plugin sends the post asynchronously through wp-cron. Maybe you can check how often this will be triggered!?!

**Comment by wadaki** [comment] 2024-10-02 23:21
I have exactly the same issue. I don't know if the plugin need the Wordpress cron, I didn't setup yet. 
But anyway, I think it's not related, because I can see the numbers of postings. There is only no content in Mastodon visible.
https://social.tchncs.de/deck/@SatoLab@satolab.ignorelist.com
https://satolab.ignorelist.com/?author=1Mein

Looks like permission issue...

**Comment by pfefferle** [comment] 2024-10-03 08:58
The number you see on mastodon has not much to do with the actual posts that show up there! Mastodon can get the number of post from an API.

One thing: Mastodon does not import old posts, only new ones that are created after someone is following the blog!

Can you provide us an example post URL so that we can have a look?

**Comment by wadaki** [comment] 2024-10-04 01:20
Thank you for explanation. Yesterday I created a new blog entry here:
https://satolab.ignorelist.com/

When I search in Mastodon my accounting "[@SatoLab@satolab.ignorelist.com](https://social.tchncs.de/deck/@SatoLab@satolab.ignorelist.com)", I can find the account, but no blog item is visible.

Please feel free to contact me if you need more information.

**Comment by pfefferle** [comment] 2024-10-04 07:22
I can see a post:

![Image](https://github.com/user-attachments/assets/d7e361c8-0615-44da-9c64-efaf7235daed)

**Comment by wadaki** [comment] 2024-10-04 07:29
This is only, because I shared by my self manual. Now I created a new "Test for Mastodon", it will not show up.

**Comment by wadaki** [comment] 2024-10-07 08:15
Maybe you are right, the cron job is important. I don't know why, but the cron job via Wordpress does not work. So I created a cron job for "www-data" user server side. As soon as it was done, the last entries were published in Mastodon. I will check in the next days.
Maybe it's a subdomain problem?

**Comment by swduncan** [comment] 2024-10-10 22:21
I have a very similar issue - blog is at swduncan.com, I recently moved from Wordpress.com where it worked fine under their business plan using the ActivityPub plugin, to self-hosting on Amazon Lightsail. The change was made a few days ago. 

I can see the profile in Mastodon as it was before the switch, but no followers and no new posts. When I try to follow the existing profile, it looks like it's taking on the Mastodon.social web interface, but on the app it says it's pending. 

Site health shows no problems. 
wp-cron is set up and running - under the www-data user
Webfinger doesn't show any issues with my profile page.

What else is there to check to debug this?

**Comment by pfefferle** [comment] 2024-10-11 06:56
@swduncan It seems that you found every possible forum to ask the question ☺️

I will answer on WordPress.org https://wordpress.org/support/topic/posts-not-posting-follows-pending-post-to-wp-json-is-404/

**Comment by jjschwarz** [comment] 2024-10-14 20:17
I appear to be suffering the same thing on multiple hosts.  Right now I am fighting with @lemonade@bellcowservices.com and the blog wide @bellcowservices.com@bellcowservices.com accounts.  They haven't shown any posts since 28 June, but nothing has really changed on the server since that time other than routine plugin updates.  The cron jobs seem to be firing off fine from the system cron via the wp-cron.php URL.  Any suggestions on next place to look?

**Comment by jjschwarz** [comment] 2024-10-14 20:43
Something similar happening at @n4jjs.com.  I seems to randomly show posts, I received some but not others.

**Comment by harcesz** [comment] 2024-12-03 23:36
Just to note - my problem was solved, it was a cron issue.

**Comment by pfefferle** [comment] 2024-12-04 10:51
@harcesz thanks for the feedback!

**Comment by wadaki** [comment] 2024-12-04 11:10
Same here. After some updates the problem is gone. Ticket can be closed.
Thanks to all who helped with this issue.

**Comment by pfefferle** [comment] 2024-12-04 11:13
I will close this then, feel free to re-open, comment or file a new issue if it might still be an issue.

**Closed by pfefferle** 2024-12-04 11:13 UTC
Labels: [Type] Bug, Needs triage
