### ISSUE TITLE
Latest Release Now Allows Injection of Jetpack Sharing/Like, In an Awful Way

### ISSUE THREAD

**Issue by timnolte** [Automattic/wordpress-activitypub#335] opened 2023-05-16 12:34 UTC
So I had may a blog post before today since the beginning of April. Something changed in the more recent releases of the plugin as now the Jetpack Sharing & Like features are being injected into my ActivityPub content. I am using a custom format.

```HTML
<p><strong>[ap_title]</strong></p>

<p>[ap_excerpt]</p>

<p>[ap_hashtags]</p>

<p>[ap_shortlink type="html"]</p>
```
I can see when I make a test `application/activity+json` request to my site that now all posts have this extra sharing content in them.

New Output with Issue:
![image](https://github.com/Automattic/wordpress-activitypub/assets/4312062/a3f7294b-af1d-4d82-9b62-6271e528660f)

Old Output, Cached on Mastodon:
![image](https://github.com/Automattic/wordpress-activitypub/assets/4312062/138d75b3-dd97-49e3-86db-a17648c3fc1e)

**Comment by jeherve** [comment] 2023-05-16 13:09
Thanks for the report!

This is indeed an annoying issue, caused by Jetpack. It is currently tracked in this issue:
https://github.com/Automattic/jetpack/issues/29435

It should be fixed in the next Jetpack release, scheduled to go out on June 6, in part thanks to this recent change in the ActivityPub plugin: #328

Since this is tracked in the Jetpack repository, I'll close this issue.

**Closed by jeherve** 2023-05-16 13:09 UTC
