### ISSUE TITLE
Bidirectional comments don't reply to the original comment

### ISSUE THREAD

**Issue by edent** [Automattic/wordpress-activitypub#638] opened 2024-01-09 10:28 UTC
### Quick summary

When I reply to a comment on my blog, it posts a new ActivityPub message - but it isn't in reply to the original comment.

### Steps to reproduce

1. Post on https://shkspr.mobi/blog/2020/03/it-is-spelled-url/
2. This person replies https://post.lurk.org/@rose_alibi/111722787436930132
3. I reply to their comment https://shkspr.mobi/blog/2020/03/it-is-spelled-url/#comment-363977
4. The reply is sent without any context https://mastodon.social/deck/@blog@shkspr.mobi/111725492490736277

![image](https://github.com/Automattic/wordpress-activitypub/assets/837136/0b0a79f5-e9b3-4d8d-851d-a750380caffa)

### What you expected to happen

My comment should be in reply to the original comment.  Or in reply to the original post.

### What actually happened

The comment has no context, so looks a bit weird. Additionally, there's no setting to suppress comments from appearing.

### Impact

One

### Available workarounds?

No but the platform is still usable

**Comment by edent** [comment] 2024-01-09 10:35
Ah! If I reply to someone who replied to my blog, it *does* thread properly.

![Screenshot showing a threaded reply](https://github.com/Automattic/wordpress-activitypub/assets/837136/e030a2c0-de89-48a2-983d-99fe7198cba0)
https://shkspr.mobi/blog/2023/12/the-joy-and-the-pity-of-making-your-own-stuff/#comment-363984

But, because it doesn't @ them, do they get notified?

This is excellent functionality! But I think it needs an option to be disabled when replying to regular comments. Otherwise there will be some very weird out of context posts.

**Comment by pfefferle** [comment] 2024-01-09 11:08
> But, because it doesn't @ them, do they get notified?

This is a known problem and I am experimenting on how to implement it nicely (I would love to have it without the @-reply thing at the beginning).

> Otherwise there will be some very weird out of context posts.

Good point!

**Comment by janboddez** [comment] 2024-01-10 13:47
> Post on https://shkspr.mobi/blog/2020/03/it-is-spelled-url/
> This person replies https://post.lurk.org/@rose_alibi/111722787436930132
> I reply to their comment https://shkspr.mobi/blog/2020/03/it-is-spelled-url/#comment-363977

I think what might have happened here is their original reply was not to your blog actor, but to the crossposted/syndicated copy under your _actual Mastodon_ account? And that Brid.gy backfed it to your blog.

It also appears that all _author/user_ comments make it back "to the Fediverse," even those (like in your example) that did not come (directly) from a "ActvitiyPub actor."

> Ah! If I reply to someone who replied to my blog, it does thread properly.

Exactly, that's been my experience, too.

**Comment by janboddez** [comment] 2024-01-10 14:10
Either way, it looks like the "real" issue (bug?) is that all of an author's comments get sent out "to the fediverse," even those not in reply to "fediverse comments."

That said, the plugin does seem to set a "inReplyTo" property: https://github.com/Automattic/wordpress-activitypub/blob/48a33b82e929725cdcd358c4b87fc188ec25764a/includes/transformer/class-comment.php#L136

Guessing Mastodon just doesn't know what to do with it?

Because I do _think_ that in _this specific case_, had the `inReplyTo` been set to the comment's fediverse URL (which I think would be stored in `webmention_source_url`, given that the comment originated as a Bridgy (?) mention), that your reply would've been threaded "OK." This _could_ be done using custom code. (Like, it's not straightforward, but I'm 100% sure it can be done.)

But the latter may not be a solution for other, "random" comments. I kinda also wanna be able to stop "irrelevant" (?) comments from being federated.

**Comment by mikewmerritt** [comment] 2024-01-10 22:39
I'm wondering if there is a larger issue here. Last month I was noticing that replies made before the latest update were often not connecting to the original post, but the behavior was inconsistent.

**Comment by pfefferle** [comment] 2024-01-11 08:04
I think this is an issue from the plugin not handling old comments properly, I am working on a fix!

**Comment by KevinGimbel** [comment] 2024-04-17 09:59
> I'm wondering if there is a larger issue here. Last month I was noticing that replies made before the latest update were often not connecting to the original post, but the behavior was inconsistent.

I'm seeing the same, second-level comments on my blog are assigned to the Home Page, not the post they were originally commented on. 

<img width="1501" alt="Screenshot 2024-04-17 at 11 58 00" src="https://github.com/Automattic/wordpress-activitypub/assets/2161714/aaab4266-c3c8-4f07-9815-ed68d27746dd">

**Comment by pfefferle** [comment] 2024-04-17 10:43
@KevinGimbel I can't see any issues on your screenshot. It shows the replies and it also lists the post properly. Do I muss something?

**Comment by KevinGimbel** [comment] 2024-04-17 10:44
Sorry, yes it's confusing. 

In my screenshot the "In response to" is wrong - the top two comments are commenting on the Home Page of my blog, the other two are replies to the "Week 19: Fallout" post (as seen in your screenshot)

**Comment by KevinGimbel** [comment] 2024-04-17 10:46
I would expect all comments to be nested under this post: https://kevingimbel.de/blog/2024/04/week-19-fallout#comments

**Comment by pfefferle** [comment] 2024-04-17 10:46
This might be because it is simply an @-mention and not a reply to a post, which is currently not really supported. This might be a feature (not a bug ☺️) if you use a single page as home page.

**Comment by KevinGimbel** [comment] 2024-04-17 10:47
Hmm I do use a single page as home page :D Should I open a feature request then? In terms of having - and preserving - conversations in the comment section it'd be good to have them properly nested

**Comment by pfefferle** [comment] 2024-04-17 10:48
Ah, now I see! No, you are completely right, this is a bug!

**Comment by pfefferle** [comment] 2024-04-17 10:51
Ah, it's because this `https://kevingimbel.de/?c=682` is pointing to your home-page instead of to the comment!

```
## Request
curl "https://kevingimbel.de/?c=682" \
     -H 'Accept: application/activity+json'
```

Do you have caching enabled?

**Comment by KevinGimbel** [comment] 2024-04-17 10:54
Yes I use the WP Super Cache Plugin, I'll check if there's anything in the settings

**Comment by KevinGimbel** [comment] 2024-04-17 10:55
Seems to work now - there was an option to not cache pages with GET parameters and now the link leads me to the comment.

**Comment by KevinGimbel** [comment] 2024-04-17 10:58
I was too excited, the curl still doesn't work it seems 🤔

**Comment by pfefferle** [comment] 2024-04-17 11:10
What plugin do you use for caching? Can you add an exception for different `Accept` headers (content negotiation)?

**Comment by KevinGimbel** [comment] 2024-04-17 11:18
I'm using https://wordpress.org/plugins/wp-super-cache/ - I'll see if I can add exceptions

**Comment by pfefferle** [comment] 2024-04-17 11:20
@donnchawp can you maybe help here?

**Comment by donnchawp** [comment] 2024-04-22 15:35
I was not able to replicate this issue on my own site. I responded to a [comment](https://odd.blog/2005/08/01/donoughmore-vintage-festival-july-31st-2005/#comment-710191) and it was seen as a reply on the first comment in the Mastodon web client. The page was cached by WP Super Cache when I commented as a logged-in user on my site.

![Screenshot 2024-04-22 at 16 29 14](https://github.com/Automattic/wordpress-activitypub/assets/5656673/169f352a-94e1-4c33-a4b9-08e4e13db2c1)

I noticed that @edent is using Litespeed cache which might have caused the problem. I'm not sure if it uses the Accept header in the cache key.

**Comment by KevinGimbel** [comment] 2024-04-23 09:43
I just tried again and it doesn't work for me.

The top comment is assigned to the home-page again (coming from a reply on Mastodon). 

<img width="801" alt="Screenshot 2024-04-23 at 11 42 09" src="https://github.com/Automattic/wordpress-activitypub/assets/2161714/b88df38e-8ce0-44c5-bb28-6ebd4143e985">

**Comment by KevinGimbel** [comment] 2024-04-23 09:46
Same with WP Super Cache disabled - the third comment is always in reply to the home-page. 

<img width="1523" alt="Screenshot 2024-04-23 at 11 45 37" src="https://github.com/Automattic/wordpress-activitypub/assets/2161714/41145f89-0db3-498a-b381-87753e53ff2b">

**Comment by KevinGimbel** [comment] 2024-08-05 08:34
The issue still persists, it just happened again. The top-most comment is a reply to the home page not the post.

<img width="1099" alt="Screenshot 2024-08-05 at 10 32 31" src="https://github.com/user-attachments/assets/75ae8fe0-c11e-4085-bd19-c696b825aa91">

**Comment by pfefferle** [comment] 2024-10-08 10:33
This should be fixed now! Please re-open if still an issue.

**Closed by pfefferle** 2024-10-08 10:33 UTC
Labels: [Type] Bug, Needs triage
