### ISSUE TITLE
Permit to disable comments from fediverse network

### ISSUE THREAD

**Issue by baby-gnu** [Automattic/wordpress-activitypub#640] opened 2024-01-09 16:42 UTC
### What

I would like to be able to avoid any comments in wordpress coming from fediverse.

### Why

I manage comment and reply to them directly in fediverse and never show them on post and pages.

**Comment by mediaformat** [comment] 2024-01-10 17:43
Duplicate of #181

**Comment by baby-gnu** [comment] 2024-01-11 10:31
> @baby-gnu For your site you can use Settings -> Discussion, or choose per-post Discussion setting (un-check allow comments).
> 
> However, fediverse users can still reply to a post, this is a protocol level issue... See: [mastodon/mastodon#8565 (comment)](https://github.com/mastodon/mastodon/issues/8565#issuecomment-1444583776)
> 
> > it's more or less stalled on protocol talks right now. the current roadblock is trying to make it work for both reply-based systems and comment-based systems, and maintaining compatibility between the two

Thanks @mediaformat, disabling discussion do not prevent wordpress to put comments to pending (and notify author):

<details><summary>The toots from fediverse are still in pending</summary>

![wordpress-activitypub-comment](https://github.com/Automattic/wordpress-activitypub/assets/1233212/335e6950-22a5-411b-9ed7-9a85707e7545)
</details>

**Comment by mediaformat** [comment] 2024-01-12 00:31
Ah I understand, you would like a setting to to drop Fediverse replies!
So would you expect that globally, per post-type or per-post?

**Comment by baby-gnu** [comment] 2024-01-12 07:54
> Ah I understand, you would like a setting to to drop Fediverse replies! So would you expect that globally, per post-type or per-post?

My use case is globally :+1:

**Comment by pfefferle** [comment] 2024-01-12 08:00
Just out of curiosity: most users prefer this plugin, because it supports federated comments, otherwise they use crossposing-plugins. Why do you prefer this plugin, even without the comment feature?

**Comment by baby-gnu** [comment] 2024-01-15 08:25
> crossposing-plugins

First, I didn't know about other plugins, I discovered the activitypub plugin by a toot on the fediverse.

I like the ability to cut&past a wordpress URL directly in my mastodon client search box to share a blog post :+1:

**Comment by mdingemanse** [comment] 2024-01-16 19:54
> I like the ability to cut&past a wordpress URL directly in my mastodon client search box to share a blog post 👍

Interesting, I hadn't realised this was a possibility @baby-gnu !

**Comment by jeherve** [comment] 2024-04-16 08:01
I'd like to add my vote to this issue.

> Just out of curiosity: most users prefer this plugin, because it supports federated comments, otherwise they use crossposing-plugins. Why do you prefer this plugin, even without the comment feature?

Personally, I've opted to disable comments on some of the posts on my site, but not all of them. When comments are open on a post, I am interested in receiving feedback, whether directly in the comments or via the Fediverse. When comments are closed for a post, I would rather not allow comments, via the site and via the Fediverse. Today folks can still leave comments via the Fediverse.

Thank you!

**********

Internal reference: p1713216236135369-slack-C0CMN0V97

**Comment by pfefferle** [comment] 2024-04-16 08:48
@jeherve I am not sure if it is a good idea, to re-use core settings for that. We had quite some discussions on the Webmentions plugin, where we tried to re-use the ping settings.

There are folks that disable comments completely, to only use Webmentions and ActivityPub feedback, there are others (like you) that want to have no feedback at all when disabling comments.

I would suggest to have it as a separate setting, where you can disable feedback from the fediverse completely and per post!?!

**Comment by pfefferle** [comment] 2024-04-16 08:50
Is it possible to hook into the "Discussion" section in the Gutenberg sidebar?

<img width="308" alt="Screenshot 2024-04-16 at 10 49 27" src="https://github.com/Automattic/wordpress-activitypub/assets/2373/f94cee66-0673-4afd-9629-dd51c320bebc">

**Comment by jeherve** [comment] 2024-04-16 10:32
> I would suggest to have it as a separate setting, where you can disable feedback from the fediverse completely and per post!?!

Yeah, that may be a good option too.

> Is it possible to hook into the "Discussion" section in the Gutenberg sidebar?

No, it is not filterable right now.

https://github.com/WordPress/gutenberg/blob/bea46cbe967bb481b12b9f20a6024d3ede609daf/packages/editor/src/components/post-discussion/panel.js#L18

You could suggest that improvement though.

**Comment by mediaformat** [comment] 2024-08-16 00:03
There are 2 ways you could might do this currently:

One is code based, using the following constant, you can disable all incoming interactions:

`define( ACTIVITYPUB_DISABLE_INCOMING_INTERACTIONS, true );`

The other way would be with a Block based theme, you can remove the Comments display block.

**Comment by pfefferle** [comment] 2024-09-23 09:48
I think the comment of @mediaformat explains all possible options.

**Closed by pfefferle** 2024-09-23 09:48 UTC
Labels: [Type] Feature Request
