### ISSUE TITLE
Federated Comments: own local comments get federated back

### ISSUE THREAD

**Issue by jeherve** [Automattic/wordpress-activitypub#932] opened 2024-10-09 07:59 UTC
### Quick summary

It seems that when I leave a comment on one of my own posts, from my site, that comment is federated and then the federated comment is copied back to my site, resulting in a duplicate comment.

### Steps to reproduce

1. Start with a site running the latest version of the ActivityPub plugin (and EMA / Friends)
2. Publish a new post
3. Add a comment to your own post right after publishing, using the comment form on your own site.
4. That comment is federated and immediately appears on the Fediverse, below the federated post.

### What you expected to happen

I would not expect anything else to happen at this point.

### What actually happened

The comment is federated back to the local site a minute later, resulting in a duplicated comment:

![Image](https://github.com/user-attachments/assets/99caa314-3288-4504-a19b-40074fad0bf7)

### Impact

All

### Available workarounds?

Yes, easy to implement

**Comment by pfefferle** [comment] 2024-10-09 09:04
Duplicate of #840

**Closed as completed by pfefferle** 2024-10-09 09:04 UTC
Labels: Bug, [Type] Duplicate
