### ISSUE TITLE
Tags are being injected into WordPress?

### ISSUE THREAD

**Issue by eiland-asbl** [Automattic/wordpress-activitypub#1105] opened 2024-12-19 22:15 UTC
### Quick summary

Not sure where it is coming from but i have a sneaky suspicion new tags are being injected into my blog through activitiypub (or @akirk's friends).
Im encoutering it on two instances.

### Steps to reproduce

Check your https://blog.com/wp-admin/edit-tags.php

### What you expected to happen

No unknown tags

### What actually happened

Many unknown tags, not linked to posts

### Impact

One

### Available workarounds?

No but the platform is still usable

**Comment by pfefferle** [comment] 2024-12-19 22:22
Can you give us some examples? Are the tags look like color codes for example?

**Comment by akirk** [comment] 2024-12-20 07:47
Sorry about this, I checked and I can confirm that it's the Friends plugin. Resp. WordPress seems automatically create tags if a hashtag is included in the post, on the wp-admin tag page it just doesn't display it because it only displays post_type `post` there but I checked and the friend posts are tagged with it.

Let's continue in https://github.com/akirk/friends/issues/418.

**Comment by akirk** [comment] 2024-12-20 08:09
Oh, it's the ActivityPub plugin after all, not Friends:
https://github.com/Automattic/wordpress-activitypub/blob/trunk/includes/class-hashtag.php#L65

**Comment by pfefferle** [comment] 2024-12-20 08:38
But it adds them to the post!

**Comment by akirk** [comment] 2024-12-20 08:55
They are linked to the posts in question indeed, just the View link in `wp-admin/edit-tags.php` doesn't show them for Friends posts because it's a different post type.

I think part of the confusion is that tags appear in `wp-admin/edit-tags.php` that were not entered by any WordPress author.

**Comment by nickbohle** [comment] 2024-12-20 09:12
Hi,  
I noticed this issue yesterday as well when I shared a podcast episode. The link I included had the title: *“Episode #123 - Lorem ipsum…”*. Upon publishing, the system automatically created the tag `#123`.  

I also remembered encountering a similar issue with color codes in the past.  

To address this, I edited the post and manually removed the `#123` tag. Then, I went to **Admin > Posts > Tags** and deleted the tag. Additionally, I navigated to **Admin > Settings > ActivityPub > Settings** and unchecked the option: *“Add hashtags in the content as native tags and replace the #tag with the tag link.”*  

Since tagging on weblogs works differently (Background:  [https://fewertags.com/research/](https://fewertags.com/research/) )than on social media, could this unchecking be the solution?

Thanks!

**Comment by akirk** [comment] 2024-12-20 09:18
FWIW in the next version of Friends you'll be able to view the tagged posts on the frontend: https://github.com/akirk/friends/pull/419

**Comment by pfefferle** [comment] 2024-12-20 09:33
This was a bug, but should be fixed now! We do no longer parse hashtags in HTML elements, like links!

@nickbohle can you verify that this does no longer happen?

**Comment by nickbohle** [comment] 2024-12-20 13:14
> This was a bug, but should be fixed now! We do no longer parse hashtags in HTML elements, like links!
> 
> [@nickbohle](https://github.com/nickbohle) can you verify that this does no longer happen?

@pfefferle 

Yes, I can confirm that. I updated an existing post and published a new one. (Version 4.5.1)

**Comment by pfefferle** [comment] 2024-12-20 13:23
You can confirm that it no longer happens?

**Comment by nickbohle** [comment] 2024-12-20 13:28
> You can confirm that it no longer happens?

Yes, I can confirm that it no longer happens.

**Comment by pfefferle** [comment] 2024-12-20 13:40
So I will close this for now. @nickbohle please re-open if you find some more cases...

**Closed as completed by pfefferle** 2024-12-20 13:40 UTC
Labels: Bug, Needs triage, [Pri] High, [Status] Escalated to Product Ambassadors
